"""Circular Swiss regression cases for adapter change detection.

Generated on 2026-07-14 with pyswisseph 2.10.03 and the official Swiss
``sepl_18.se1``, ``semo_18.se1`` and ``seas_18.se1`` files, Lahiri ayanamsa,
true nodes, geocentric positions and Placidus houses. These values are a
reproducibility fixture generated by the same engine under test, not an
independent oracle and not validation of Swiss Ephemeris or Swiss-backed tools.
"""

from __future__ import annotations

REFERENCE_GROUPS = (
    (
        "aries-ingress",
        "2024-04-13T20:30:00+05:30",
        12.97,
        77.59,
        ("sign-boundary", "ingress"),
        {
            "Sun": (359.976589743, 0.980052916, 11, 26, 4),
            "Moon": (64.295333066, 13.209515070, 2, 4, 4),
            "Rahu": (351.382903669, -0.013598006, 11, 26, 2),
        },
    ),
    (
        "mercury-station-rx",
        "2024-04-01T22:15:00-04:00",
        40.71,
        -74.0,
        ("station", "retrograde"),
        {
            "Mercury": (3.022501807, -0.019746558, 0, 0, 1),
            "Sun": (348.637090494, 0.986346714, 11, 26, 1),
            "Moon": (258.117636179, 13.501416934, 8, 19, 2),
        },
    ),
    (
        "mercury-station-direct",
        "2024-04-25T08:54:00-04:00",
        40.71,
        -74.0,
        ("station", "direction-change"),
        {
            "Mercury": (351.786020530, -0.000051084, 11, 26, 2),
            "Sun": (11.608753488, 0.973159573, 0, 0, 4),
            "Moon": (209.160942437, 12.483757442, 6, 15, 3),
        },
    ),
    (
        "jupiter-station",
        "2024-10-09T07:05:00+01:00",
        53.35,
        -6.26,
        ("station", "timezone"),
        {
            "Jupiter": (57.135344827, 0.000076583, 1, 4, 2),
            "Moon": (243.916834668, 12.674400859, 8, 18, 2),
            "Rahu": (342.367729769, -0.012339348, 11, 25, 3),
        },
    ),
    (
        "saturn-station",
        "2024-06-29T21:00:00+01:00",
        51.5,
        -0.12,
        ("station", "slow-body"),
        {
            "Saturn": (325.229633376, -0.000089412, 10, 24, 2),
            "Moon": (356.448072409, 14.052268534, 11, 26, 3),
            "Rahu": (347.310978738, -0.006539134, 11, 26, 1),
        },
    ),
    (
        "dst-us-before",
        "2024-03-10T01:59:00-05:00",
        40.71,
        -74.0,
        ("dst", "timezone", "before-transition"),
        {
            "Moon": (324.799161101, 15.260754355, 10, 24, 2),
            "Mercury": (336.041415718, 1.923060843, 11, 25, 1),
            "Rahu": (351.541617868, -0.038041813, 11, 26, 2),
        },
    ),
    (
        "dst-us-after",
        "2024-03-10T03:01:00-04:00",
        40.71,
        -74.0,
        ("dst", "timezone", "after-transition"),
        {
            "Moon": (324.820356668, 15.260718511, 10, 24, 2),
            "Mercury": (336.044086627, 1.923042085, 11, 25, 1),
            "Rahu": (351.541565052, -0.038011728, 11, 26, 2),
        },
    ),
    (
        "dst-eu-before",
        "2024-03-31T00:59:00+00:00",
        53.35,
        -6.26,
        ("dst", "timezone", "before-transition"),
        {
            "Moon": (231.143179115, 12.807204227, 7, 17, 2),
            "Venus": (329.470134835, 1.236134313, 10, 24, 3),
            "Rahu": (351.422730419, 0.007056123, 11, 26, 2),
        },
    ),
    (
        "dst-eu-after",
        "2024-03-31T02:01:00+01:00",
        53.35,
        -6.26,
        ("dst", "timezone", "after-transition"),
        {
            "Moon": (231.160967115, 12.807614144, 7, 17, 2),
            "Venus": (329.471851688, 1.236134219, 10, 24, 3),
            "Rahu": (351.422740216, 0.007050908, 11, 26, 2),
        },
    ),
    (
        "node-true-sample",
        "2000-01-01T12:00:00+00:00",
        0.0,
        0.0,
        ("node", "historical-epoch"),
        {
            "Rahu": (100.100800353, -0.054775865, 3, 7, 3),
            "Ketu": (280.100800353, -0.054775865, 9, 21, 1),
            "Moon": (199.470528960, 12.021309963, 6, 14, 4),
        },
    ),
    (
        "historical",
        "1950-06-15T23:59:30+05:30",
        19.08,
        72.88,
        ("historical", "second-resolution"),
        {
            "Moon": (62.124811220, 12.184906407, 2, 4, 3),
            "Saturn": (140.252743109, 0.052093791, 4, 10, 3),
            "Rahu": (340.690634008, -0.223434611, 11, 25, 3),
        },
    ),
    (
        "future",
        "2050-12-31T23:59:30+13:00",
        -36.85,
        174.76,
        ("future", "dateline", "second-resolution"),
        {
            "Moon": (113.562916172, 12.376258112, 3, 8, 3),
            "Jupiter": (131.134736933, -0.032078373, 4, 9, 4),
            "Rahu": (195.147481342, -0.166537040, 6, 14, 3),
        },
    ),
)

REFERENCE_PROVENANCE = (
    "pyswisseph 2.10.03",
    "official Swiss .se1 files",
    "generated 2026-07-14",
    "circular regression fixture; not an independent oracle",
)
