"""Versioned contracts for the canonical forecasting pipeline.

This package is additive.  Legacy prediction engines should produce these
contracts only after an explicit adapter is introduced.
"""

from .adapters import (
    AdaptedRulePack,
    AdapterContext,
    CandidateFieldMap,
    DirectionalConflict,
    EvidenceFieldMap,
    LegacyAdapterError,
    LegacyRulePackAdapter,
    ResearchAdaptedRulePack,
    ResearchCandidateRecord,
    ResearchEvidenceRecord,
    RulePackDescriptor,
    adapt_rule_pack_output,
    adapt_rule_pack_output_for_research,
)
from .contracts import (
    Abstention,
    AbstentionCode,
    BirthTimeSensitivity,
    CalculationProvenance,
    CertaintyTier,
    EventCandidate,
    EvidenceDirection,
    ForecastClaim,
    ForecastMode,
    ForecastPolarity,
    ProbabilityStatus,
    RuleEvidence,
    TemporalGranularity,
    TimingWindow,
    UncertaintyAssessment,
)
from .ledger import (
    ConsentAction,
    ConsentRecord,
    ConsentRequiredError,
    ForecastResolution,
    ImmutableLedgerError,
    IssuedForecast,
    LedgerDisabledError,
    LedgerError,
    ModelRelease,
    OutcomeObservation,
    OutcomeStatus,
    SQLiteForecastLedger,
    SubjectErasedError,
    SubjectExport,
)
from .pipeline import EvidencePipeline
from .replay import ReplayRecord, artifact_hash
from .research import (
    NativeScore,
    ResearchArtifactOrigin,
    ResearchSignalArtifact,
    tolerant_raw_value,
)
from .service import (
    ForecastBriefResponse,
    ForecastClaimSummary,
    ForecastReleaseMetadata,
    ForecastShadowResponse,
    process_forecast_claim,
)
from .taxonomy import (
    EVENT_TAXONOMY,
    EventCode,
    EventDefinition,
    EventDomain,
    EventSensitivity,
    get_event_definition,
)

__all__ = [
    "EVENT_TAXONOMY",
    "Abstention",
    "AbstentionCode",
    "BirthTimeSensitivity",
    "CalculationProvenance",
    "CertaintyTier",
    "EventCandidate",
    "EventCode",
    "EventDefinition",
    "EventDomain",
    "EventSensitivity",
    "EvidenceDirection",
    "ForecastClaim",
    "ForecastMode",
    "ForecastPolarity",
    "ProbabilityStatus",
    "RuleEvidence",
    "TemporalGranularity",
    "TimingWindow",
    "UncertaintyAssessment",
    "get_event_definition",
    "AdaptedRulePack",
    "AdapterContext",
    "CandidateFieldMap",
    "DirectionalConflict",
    "EvidenceFieldMap",
    "EvidencePipeline",
    "LegacyAdapterError",
    "LegacyRulePackAdapter",
    "NativeScore",
    "ResearchArtifactOrigin",
    "ResearchSignalArtifact",
    "ResearchAdaptedRulePack",
    "ResearchCandidateRecord",
    "ResearchEvidenceRecord",
    "ReplayRecord",
    "RulePackDescriptor",
    "adapt_rule_pack_output",
    "adapt_rule_pack_output_for_research",
    "artifact_hash",
    "tolerant_raw_value",
    "ConsentAction",
    "ConsentRecord",
    "ConsentRequiredError",
    "ForecastResolution",
    "ImmutableLedgerError",
    "IssuedForecast",
    "LedgerDisabledError",
    "LedgerError",
    "ModelRelease",
    "OutcomeObservation",
    "OutcomeStatus",
    "SQLiteForecastLedger",
    "SubjectErasedError",
    "SubjectExport",
    "ForecastBriefResponse",
    "ForecastClaimSummary",
    "ForecastReleaseMetadata",
    "ForecastShadowResponse",
    "process_forecast_claim",
]
